### PR TITLE
Directly convert validation errors to db::Error::ValidationError

### PR DESCRIPTION
**Pull request by hdoordt**

### CODE REVIEW

**Comment by marcoow** [comment]
Where is the conversion happening though?

**Comment by hdoordt** [comment]
Right here: https://github.com/mainmatter/gerust/blob/main/blueprint/db/src/lib.rs#L51-L53. Specifically, the `#[from]` attributes generates `impl From<validator::ValidationErrors> for Error`

**Comment by marcoow** [comment]
ah, I see - I was looking for that in this PR, wasn't aware that was in `main` already

**Review by marcoow — APPROVED** [review]

**Comment by hdoordt** [comment]
Yeah I think something went wrong with merging there.

**Pull request merged**
