### PR TITLE
Fix `og` data

### PR DESCRIPTION
**Pull request by marcoow**
This:

* fixes the URL (https://gerust.rs instead of https://docs.gerust.rs)
* fixes the description

## TODO

- [x] add `og:image`
- [x] improve favicon (the current one doesn't work quite well(

### CODE REVIEW

**Comment by marcoow** [comment]
@umbrellarocket we need an `og:image` for this – can you make one?

It should include:

* the logo
* sub-headline: _"A project generator and manager for Rust backend projects."_
* smaller text somewhere below: _"Gerust takes care of the accidental complexity of Rust backend projects so you can stay focused on what matters."_
* "by Mainmatter" somewhere at the bottom with our logo

I'd like to release this tomorrow or Thursday so we'd need the image by then

**Comment by marcoow** [comment]
I think the favicon works well. For the `og:image`, can we use Version 2 but add the text "A generator for Rust backend projects" (slightly different and shorter than what we had so far) to the left side where the image is?

**Comment by umbrellarocket** [comment]
I'm assuming you also meant we'd remove the headline from the right side. If so, here's the image preview: 
image

**Comment by marcoow** [comment]
yes, that's what I meant

**Comment by marcoow** [comment]
can you upload the favicon here as well?

**Comment by umbrellarocket** [comment]
gerust_icon

**Pull request merged**
